-- Add 40 natural/fresh juice varieties to the shared product library
-- (category: عصائر). Distinct from the 11 juice items already seeded.

INSERT INTO public.shared_menu_products (id, name, category, created_at, updated_at) VALUES
(gen_random_uuid(), 'عصير ليمون', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير كيوي', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير بطيخ', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير شمام', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير عنب', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير خوخ', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير مشمش', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير كرز', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير توت', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير أفوكادو', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير موز', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير جريب فروت', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير يوسفي', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير كمثرى', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير تين', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير باشن فروت', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير دراغون فروت', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير كيوي فراولة', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير فراولة موز', 'عصائر', now(), now()),
(gen_random_uuid(), 'كوكتيل مانجو فراولة', 'عصائر', now(), now()),
(gen_random_uuid(), 'كوكتيل أناناس فراولة', 'عصائر', now(), now()),
(gen_random_uuid(), 'كوكتيل مانجو أناناس', 'عصائر', now(), now()),
(gen_random_uuid(), 'كوكتيل توت مشكل', 'عصائر', now(), now()),
(gen_random_uuid(), 'كوكتيل استوائي', 'عصائر', now(), now()),
(gen_random_uuid(), 'كوكتيل رمان فراولة', 'عصائر', now(), now()),
(gen_random_uuid(), 'كوكتيل ليمون نعناع فراولة', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير خيار بالنعناع', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير زنجبيل ليمون', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير تمر هندي', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير قصب السكر', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير الصبار', 'عصائر', now(), now()),
(gen_random_uuid(), 'سموذي مانجو', 'عصائر', now(), now()),
(gen_random_uuid(), 'سموذي فراولة', 'عصائر', now(), now()),
(gen_random_uuid(), 'سموذي أفوكادو', 'عصائر', now(), now()),
(gen_random_uuid(), 'سموذي موز فراولة', 'عصائر', now(), now()),
(gen_random_uuid(), 'سموذي توت مشكل', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير برتقال جزر', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير تفاح جزر زنجبيل', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير رمان تفاح', 'عصائر', now(), now()),
(gen_random_uuid(), 'عصير جوز الهند', 'عصائر', now(), now());
