import type { Profile, Restaurant, Subscription, MenuItem, Offer, Branch, Review, Tool, ActivationCode, Plan, Application } from './types';

const now = new Date().toISOString();
const oneYearLater = new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString();
const hundredYearsLater = new Date(Date.now() + 100 * 365 * 24 * 60 * 60 * 1000).toISOString();

// ── Mock Users ──────────────────────────────────────────────────────────────
export const MOCK_USERS: Record<string, { password: string; profile: Profile }> = {
  'owner@mershhah.com': {
    password: '123456',
    profile: {
      id: 'owner-001',
      full_name: 'مالك المطعم',
      email: 'owner@mershhah.com',
      phone_number: '+966501234567',
      role: 'owner',
      account_status: 'active',
      restaurant_name: 'مطعم الشيف أحمد',
      restaurant_id: 'rest-001',
      admin_permissions: [],
      ai_trial_used: false,
      created_at: now,
      updated_at: now,
    },
  },
  'admin@mershhah.com': {
    password: '123456',
    profile: {
      id: 'admin-001',
      full_name: 'مدير النظام',
      email: 'admin@mershhah.com',
      phone_number: '+966509876543',
      role: 'admin',
      account_status: 'active',
      restaurant_name: null,
      restaurant_id: null,
      admin_permissions: [
        'dashboard', 'management', 'financials', 'store-management',
        'applications', 'announcements', 'support', 'team', 'workflow', 'sales',
      ],
      ai_trial_used: false,
      created_at: now,
      updated_at: now,
    },
  },
};

// ── Mock Restaurants ────────────────────────────────────────────────────────
export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-001',
    owner_id: 'owner-001',
    name: 'مطعم الشيف أحمد',
    name_en: 'Chef Ahmed Restaurant',
    username: 'chef-ahmed',
    description: 'أفضل المأكولات الشرقية والغربية في جدة',
    description_en: 'Best Eastern and Western cuisine in Jeddah',
    logo: null,
    primaryColor: '#6366F1',
    secondaryColor: '#F3F4F6',
    buttonTextColor: '#FFFFFF',
    borderRadius: 12,
    fontFamily: 'Cairo',
    socialLinks: null,
    deliveryApps: null,
    aiConfig: null,
    created_at: now,
    updated_at: now,
    is_paid_plan: false,
    analysis_daily_count: 0,
    analysis_reviews_daily_count: 0,
    pulse_daily_count: 0,
    reply_templates_daily_count: 0,
    feedback_summary_daily_count: 0,
    content_writer_daily_count: 0,
    image_generation_daily_count: 0,
    maps_search_daily_count: 0,
    maps_details_daily_count: 0,
    menu_import_monthly_count: 0,
  },
];

// ── Mock Subscriptions ──────────────────────────────────────────────────────
export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-001',
    profile_id: 'owner-001',
    plan_id: 'free',
    plan_name: 'الباقة المجانية',
    status: 'active',
    start_date: now,
    end_date: hundredYearsLater,
  },
  {
    id: 'sub-002',
    profile_id: 'admin-001',
    plan_id: 'free',
    plan_name: 'الباقة المجانية',
    status: 'active',
    start_date: now,
    end_date: hundredYearsLater,
  },
];

// ── Mock Menu Items ─────────────────────────────────────────────────────────
export const MOCK_MENU_ITEMS: MenuItem[] = [
  {
    id: 'item-001',
    name: 'كبسة لحم',
    name_en: 'Lamb Kabsa',
    description: 'كبسة لحم مع الأرز والبهارات العربية',
    description_en: 'Lamb kabsa with rice and Arabic spices',
    category: 'الأطباق الرئيسية',
    category_en: 'Main Courses',
    image_url: '',
    status: 'available',
    display_tags: 'best_seller',
    sizes: [
      { id: 'size-001', name: 'regular', price: 45, cost: 18, calories: 650 },
      { id: 'size-002', name: 'large', price: 65, cost: 25, calories: 950 },
    ],
    restaurant_id: 'rest-001',
    position: 1,
    clicks_count: 120,
    profit: 27,
    profitMargin: 60,
    popularity: 85,
    classification: 'Star',
    createdAt: now,
  },
  {
    id: 'item-002',
    name: 'برياني دجاج',
    name_en: 'Chicken Biryani',
    description: 'برياني دجاج هندي مع الزعفران',
    description_en: 'Indian chicken biryani with saffron',
    category: 'الأطباق الرئيسية',
    category_en: 'Main Courses',
    image_url: '',
    status: 'available',
    display_tags: 'new',
    sizes: [
      { id: 'size-003', name: 'regular', price: 38, cost: 14, calories: 580 },
    ],
    restaurant_id: 'rest-001',
    position: 2,
    clicks_count: 85,
    profit: 24,
    profitMargin: 63,
    popularity: 72,
    classification: 'Star',
    createdAt: now,
  },
  {
    id: 'item-003',
    name: 'فاهيتا دجاج',
    name_en: 'Chicken Fajita',
    description: 'شريحة دجاج مشوية مع الخضار والتورتيلا',
    description_en: 'Grilled chicken strips with veggies and tortilla',
    category: 'الوجبات السريعة',
    category_en: 'Fast Food',
    image_url: '',
    status: 'available',
    display_tags: 'none',
    sizes: [
      { id: 'size-004', name: 'regular', price: 32, cost: 12, calories: 450 },
      { id: 'size-005', name: 'large', price: 48, cost: 18, calories: 680 },
    ],
    restaurant_id: 'rest-001',
    position: 3,
    clicks_count: 65,
    profit: 20,
    profitMargin: 62,
    popularity: 55,
    classification: 'Plow-Horse',
    createdAt: now,
  },
  {
    id: 'item-004',
    name: 'شاورما عربي',
    name_en: 'Arabic Shawarma',
    description: 'شاورما دجاج مع الثومية والخضار',
    description_en: 'Chicken shawarma with garlic sauce and veggies',
    category: 'الوجبات السريعة',
    category_en: 'Fast Food',
    image_url: '',
    status: 'available',
    display_tags: 'best_seller',
    sizes: [
      { id: 'size-006', name: 'regular', price: 18, cost: 6, calories: 320 },
    ],
    restaurant_id: 'rest-001',
    position: 4,
    clicks_count: 210,
    profit: 12,
    profitMargin: 67,
    popularity: 92,
    classification: 'Star',
    createdAt: now,
  },
  {
    id: 'item-005',
    name: 'عصير برتقال طبيعي',
    name_en: 'Fresh Orange Juice',
    description: 'عصير برتقال طازج 100%',
    description_en: '100% fresh orange juice',
    category: 'المشروبات',
    category_en: 'Beverages',
    image_url: '',
    status: 'available',
    display_tags: 'none',
    sizes: [
      { id: 'size-007', name: 'كوب', price: 12, cost: 4, calories: 120 },
      { id: 'size-008', name: 'براد', price: 25, cost: 8, calories: 250 },
    ],
    restaurant_id: 'rest-001',
    position: 5,
    clicks_count: 180,
    profit: 8,
    profitMargin: 67,
    popularity: 78,
    classification: 'Plow-Horse',
    createdAt: now,
  },
  {
    id: 'item-006',
    name: 'حلويات مشكلة',
    name_en: 'Mixed Desserts',
    description: 'تشكيلة من الحلويات العربية والغربية',
    description_en: 'Selection of Arabic and Western desserts',
    category: 'الحلويات',
    category_en: 'Desserts',
    image_url: '',
    status: 'available',
    display_tags: 'daily_offer',
    sizes: [
      { id: 'size-009', name: 'صغير', price: 15, cost: 5, calories: 280 },
      { id: 'size-010', name: 'كبير', price: 28, cost: 10, calories: 520 },
    ],
    restaurant_id: 'rest-001',
    position: 6,
    clicks_count: 95,
    profit: 18,
    profitMargin: 64,
    popularity: 65,
    classification: 'Puzzle',
    createdAt: now,
  },
];

// ── Mock Offers ─────────────────────────────────────────────────────────────
export const MOCK_OFFERS: Offer[] = [
  {
    id: 'offer-001',
    title: 'خصم 20% على الطلب الأول',
    title_en: '20% Off First Order',
    description: 'استمتع بخصم 20% على طلبك الأول عند استخدام كود welcome20',
    description_en: 'Enjoy 20% off your first order with code welcome20',
    image_url: '',
    external_link: null,
    valid_until: oneYearLater,
    status: 'active',
    restaurant_id: 'rest-001',
    items: ['item-001', 'item-002'],
    views_count: 250,
    clicks_count: 45,
    link_clicks_count: 12,
  },
  {
    id: 'offer-002',
    title: 'وجبة عائلية بـ 120 ريال',
    title_en: 'Family Meal for 120 SAR',
    description: 'كبسة لحم + برياني دجاج + 2 مشروب + حلوى - لكامل العائلة!',
    description_en: 'Lamb kabsa + Chicken biryani + 2 drinks + dessert - for the whole family!',
    image_url: '',
    external_link: null,
    valid_until: oneYearLater,
    status: 'active',
    restaurant_id: 'rest-001',
    items: [],
    views_count: 180,
    clicks_count: 32,
    link_clicks_count: 8,
  },
];

// ── Mock Branches ───────────────────────────────────────────────────────────
export const MOCK_BRANCHES: Branch[] = [
  {
    id: 'branch-001',
    restaurant_id: 'rest-001',
    name: 'الفرع الرئيسي',
    name_en: 'Main Branch',
    city: 'جدة',
    city_en: 'Jeddah',
    district: 'الروضة',
    district_en: 'Al Rawdah',
    address: 'شارع الأمير سلطان، حي الروضة',
    address_en: 'Prince Sultan Street, Al Rawdah',
    phone: '+966123456789',
    google_maps_url: 'https://maps.app.goo.gl/abc123',
    opening_hours: 'يوميًا 9:00 ص - 11:00 م',
    opening_hours_en: 'Daily 9:00 AM - 11:00 PM',
    status: 'active',
    latitude: 21.5433,
    longitude: 39.1728,
  },
  {
    id: 'branch-002',
    restaurant_id: 'rest-001',
    name: 'فرع التحلية',
    name_en: 'Tahlia Branch',
    city: 'جدة',
    city_en: 'Jeddah',
    district: 'التحلية',
    district_en: 'Al Tahlia',
    address: 'شارع التحلية، حي الروضة',
    address_en: 'Tahlia Street, Al Rawdah',
    phone: '+966123456790',
    google_maps_url: null,
    opening_hours: 'يوميًا 10:00 ص - 12:00 م',
    opening_hours_en: 'Daily 10:00 AM - 12:00 AM',
    status: 'active',
    latitude: 21.5530,
    longitude: 39.1620,
  },
  {
    id: 'branch-003',
    restaurant_id: 'rest-001',
    name: 'فرع المحمدية',
    name_en: 'Al Mohammedia Branch',
    city: 'جدة',
    city_en: 'Jeddah',
    district: 'المحمدية',
    district_en: 'Al Mohammedia',
    address: 'شارع فلسطين، حي المحمدية',
    address_en: 'Palestine Street, Al Mohammedia',
    phone: '+966123456791',
    google_maps_url: null,
    opening_hours: 'يوميًا 8:00 ص - 11:00 م',
    opening_hours_en: 'Daily 8:00 AM - 11:00 PM',
    status: 'active',
    latitude: 21.5720,
    longitude: 39.1450,
  },
  {
    id: 'branch-004',
    restaurant_id: 'rest-001',
    name: 'فرع النزهة',
    name_en: 'Al Nahda Branch',
    city: 'جدة',
    city_en: 'Jeddah',
    district: 'النزهة',
    district_en: 'Al Nahda',
    address: 'شارع الأمير سلطان، حي النزهة',
    address_en: 'Prince Sultan Street, Al Nahda',
    phone: '+966123456792',
    google_maps_url: null,
    opening_hours: 'يوميًا 9:00 ص - 10:00 م',
    opening_hours_en: 'Daily 9:00 AM - 10:00 PM',
    status: 'active',
    latitude: 21.5850,
    longitude: 39.1280,
  },
  {
    id: 'branch-005',
    restaurant_id: 'rest-001',
    name: 'فرع الأندلس',
    name_en: 'Al Andalus Branch',
    city: 'جدة',
    city_en: 'Jeddah',
    district: 'الأندلس',
    district_en: 'Al Andalus',
    address: 'شارع الأمير سلطان، حي الأندلس',
    address_en: 'Prince Sultan Street, Al Andalus',
    phone: '+966123456793',
    google_maps_url: null,
    opening_hours: 'يوميًا 10:00 ص - 11:00 م',
    opening_hours_en: 'Daily 10:00 AM - 11:00 PM',
    status: 'active',
    latitude: 21.5310,
    longitude: 39.1560,
  },
  {
    id: 'branch-006',
    restaurant_id: 'rest-001',
    name: 'فرع الحمراء',
    name_en: 'Al Hamra Branch',
    city: 'جدة',
    city_en: 'Jeddah',
    district: 'الحمراء',
    district_en: 'Al Hamra',
    address: 'شارع التحلية، حي الحمراء',
    address_en: 'Tahlia Street, Al Hamra',
    phone: '+966123456794',
    google_maps_url: null,
    opening_hours: 'يوميًا 9:00 ص - 12:00 م',
    opening_hours_en: 'Daily 9:00 AM - 12:00 AM',
    status: 'active',
    latitude: 21.5600,
    longitude: 39.1700,
  },
];

// ── Mock Reviews ────────────────────────────────────────────────────────────
export const MOCK_REVIEWS: Review[] = [
  {
    id: 'review-001',
    restaurant_id: 'rest-001',
    rating: 5,
    comment: 'مطعم رائع! الأكل لذيذ والخدمة ممتازة',
    createdAt: now,
    is_visible: true,
  },
  {
    id: 'review-002',
    restaurant_id: 'rest-001',
    rating: 4,
    comment: 'الكبسة ممتازة لكن التوصيل كان بطيء شوي',
    createdAt: now,
    is_visible: true,
  },
  {
    id: 'review-003',
    restaurant_id: 'rest-001',
    rating: 5,
    comment: 'من أفضل المطاعم في جدة! أنصح الجميع بتجربته',
    createdAt: now,
    is_visible: true,
  },
];

// ── Mock Tools ──────────────────────────────────────────────────────────────
export const MOCK_TOOLS: Tool[] = [
  {
    id: 'tool-001',
    title: 'تحليل المبيعات',
    title_en: 'Sales Analytics',
    description: 'تحليل مبيعاتك وتحديد الاتجاهات والفرص',
    description_en: 'Analyze your sales and identify trends and opportunities',
    category: 'analytics',
    price_label: 'مجاني',
    price_label_en: 'Free',
    icon: 'BarChart3',
    color: '#6366F1',
    bg_color: '#EEF2FF',
    popular: true,
    type: 'free',
  },
  {
    id: 'tool-002',
    title: 'مولد الصور بالذكاء الاصطناعي',
    title_en: 'AI Image Generator',
    description: 'إنشاء صور احترافية لأطباقك باستخدام الذكاء الاصطناعي',
    description_en: 'Generate professional images for your dishes using AI',
    category: 'marketing',
    price_label: 'مدفوع',
    price_label_en: 'Paid',
    icon: 'Image',
    color: '#EC4899',
    bg_color: '#FDF2F8',
    popular: true,
    type: 'paid',
  },
  {
    id: 'tool-003',
    title: 'مساعد لوحة التحكم',
    title_en: 'Dashboard Assistant',
    description: 'مساعد ذكي يساعدك في إدارة مطعمك',
    description_en: 'Smart assistant to help you manage your restaurant',
    category: 'operations',
    price_label: 'مجاني',
    price_label_en: 'Free',
    icon: 'Bot',
    color: '#10B981',
    bg_color: '#ECFDF5',
    popular: false,
    type: 'free',
  },
];

// ── Mock Plans ──────────────────────────────────────────────────────────────
export const MOCK_PLANS: Plan[] = [
  {
    id: 'free',
    name: 'الباقة المجانية',
    name_en: 'Free Plan',
    description: 'للتجربة - تتضمن ميزات أساسية',
    description_en: 'For testing - includes basic features',
    price: 0,
    duration_months: 12,
    is_active: true,
    is_featured: false,
  },
  {
    id: 'pro',
    name: 'الباقة الاحترافية',
    name_en: 'Pro Plan',
    description: 'للمطاعم الناشئة - جميع الميزات بدون حدود',
    description_en: 'For emerging restaurants - all features unlimited',
    price: 99,
    duration_months: 1,
    is_active: true,
    is_featured: true,
  },
  {
    id: 'enterprise',
    name: 'باقة المؤسسات',
    name_en: 'Enterprise Plan',
    description: 'للمطاعم الكبيرة - دعم مخصص وتقارير متقدمة',
    description_en: 'For large restaurants - dedicated support and advanced reports',
    price: 299,
    duration_months: 1,
    is_active: true,
    is_featured: false,
  },
];

// ── Mock Applications ──────────────────────────────────────────────────────
export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'jahez',
    name: 'جاهز',
    platform_id: 'jahez',
    logo_url: '',
    category: 'delivery',
  },
  {
    id: 'hungrynife',
    name: 'شفرة',
    platform_id: 'hungrynife',
    logo_url: '',
    category: 'delivery',
  },
  {
    id: 'tomato',
    name: 'طماطمة',
    platform_id: 'tomato',
    logo_url: '',
    category: 'delivery',
  },
  {
    id: 'mrsolim',
    name: ' مستر سليم',
    platform_id: 'mrsolim',
    logo_url: '',
    category: 'loyalty',
  },
  {
    id: 'tiqani',
    name: 'تِقني',
    platform_id: 'tiqani',
    logo_url: '',
    category: 'payment',
  },
];

// ── Mock Support Tickets ─────────────────────────────────────────────────────
export const MOCK_TICKETS: any[] = [
  {
    id: 'ticket-001',
    restaurant_id: 'rest-001',
    restaurant_name: 'مطعم الشيف أحمد',
    name: 'عبدالله الشمري',
    email: '',
    phone: '0551234567',
    subject: 'تأخير الطلب',
    message: 'طلبتي من المطعم وكانت الطلبية تأخرت أكثر من ساعة ولم يتم التواصل معي',
    category: 'complaint',
    status: 'open',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ticket-002',
    restaurant_id: 'rest-001',
    restaurant_name: 'مطعم الشيف أحمد',
    name: 'فاطمة العلي',
    email: '',
    phone: '0569876543',
    subject: 'هل لديكم خيارات نباتية؟',
    message: 'أبحث عن وجبات نباتية هل يمكنكم توفيرها؟',
    category: 'inquiry',
    status: 'contacted',
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ticket-003',
    restaurant_id: 'rest-001',
    restaurant_name: 'مطعم الشيف أحمد',
    name: 'محمد العتيبي',
    email: '',
    phone: '0544567890',
    subject: 'طلب توظيف',
    message: 'أبي أشتغل عندكم كطباخ عندي خبرة 5 سنوات في المطابخ العالمية',
    category: 'employment',
    status: 'open',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ticket-004',
    restaurant_id: 'rest-001',
    restaurant_name: 'مطعم الشيف أحمد',
    name: 'سارة الحربي',
    email: '',
    phone: '0533214567',
    subject: 'اقتراح توصيل',
    message: 'لو تضيفون خدمة توصيل للمنطقة الصناعية بتكون ممتازة لأنها قريبة منكم',
    category: 'suggestion',
    status: 'resolved',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ticket-005',
    restaurant_id: 'rest-001',
    restaurant_name: 'مطعم الشيف أحمد',
    name: 'خالد المطيري',
    email: '',
    phone: '0522334455',
    subject: 'استفسار عن القائمة',
    message: 'هل عندكم عروض للعائلات؟ وكم سعر صينية العائلة؟',
    category: 'other',
    status: 'closed',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
